artifact_location: file:///C:/Users/jagan/Documents/coding/MLops-DDOS/mlflow-sklearn-experiment/model_tracking/960110690696793417
creation_time: 1768379969729
experiment_id: '960110690696793417'
last_update_time: 1768379969729
lifecycle_stage: active
name: sklearn_experiment
