artifact_location: file:///C:/Users/jagan/Documents/coding/MLops-DDOS/mlflow-sklearn-experiment/model_tracking/0
creation_time: 1768379969717
experiment_id: '0'
last_update_time: 1768379969717
lifecycle_stage: active
name: Default
